//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalizedHelpPage.Areas.HelpPage.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HelpPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalizedHelpPage.Areas.HelpPage.Resources.HelpPageResources", typeof(HelpPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boolean.
        /// </summary>
        public static string Boolean {
            get {
                return ResourceManager.GetString("Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byte.
        /// </summary>
        public static string Byte {
            get {
                return ResourceManager.GetString("Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to character.
        /// </summary>
        public static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type: {0}.
        /// </summary>
        public static string DataTypeAttributeFormat {
            get {
                return ResourceManager.GetString("DataTypeAttributeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string DateTimeOffset {
            get {
                return ResourceManager.GetString("DateTimeOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decimal number.
        /// </summary>
        public static string Decimal {
            get {
                return ResourceManager.GetString("Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value is {0}.
        /// </summary>
        public static string DefaultValueFormat {
            get {
                return ResourceManager.GetString("DefaultValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to globally unique identifier.
        /// </summary>
        public static string Guid {
            get {
                return ResourceManager.GetString("Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to integer.
        /// </summary>
        public static string Integer {
            get {
                return ResourceManager.GetString("Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length: {0}.
        /// </summary>
        public static string MaxLengthAttributeFormat {
            get {
                return ResourceManager.GetString("MaxLengthAttributeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min length: {0}.
        /// </summary>
        public static string MinLengthAttributeFormat {
            get {
                return ResourceManager.GetString("MinLengthAttributeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range: inclusive between {0} and {1}.
        /// </summary>
        public static string RangeAttributeFormat {
            get {
                return ResourceManager.GetString("RangeAttributeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching regular expression pattern: {0}.
        /// </summary>
        public static string RegularExpressionAttributeFormat {
            get {
                return ResourceManager.GetString("RegularExpressionAttributeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string RequiredAttribute {
            get {
                return ResourceManager.GetString("RequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signed byte.
        /// </summary>
        public static string SignedByte {
            get {
                return ResourceManager.GetString("SignedByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String length: inclusive between {0} and {1}.
        /// </summary>
        public static string StringLengthAttributeFormat {
            get {
                return ResourceManager.GetString("StringLengthAttributeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time interval.
        /// </summary>
        public static string TimeSpan {
            get {
                return ResourceManager.GetString("TimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsigned integer.
        /// </summary>
        public static string UnsignedInteger {
            get {
                return ResourceManager.GetString("UnsignedInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI.
        /// </summary>
        public static string URI {
            get {
                return ResourceManager.GetString("URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information.
        /// </summary>
        public static string Views_AdditionalInformation {
            get {
                return ResourceManager.GetString("Views_AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string Views_And {
            get {
                return ResourceManager.GetString("Views_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API.
        /// </summary>
        public static string Views_API {
            get {
                return ResourceManager.GetString("Views_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a general description of your APIs here..
        /// </summary>
        public static string Views_APIDescription {
            get {
                return ResourceManager.GetString("Views_APIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Parameters.
        /// </summary>
        public static string Views_BodyParameters {
            get {
                return ResourceManager.GetString("Views_BodyParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection of.
        /// </summary>
        public static string Views_CollectionOf {
            get {
                return ResourceManager.GetString("Views_CollectionOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Views_Description {
            get {
                return ResourceManager.GetString("Views_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary of.
        /// </summary>
        public static string Views_DictionaryOf {
            get {
                return ResourceManager.GetString("Views_DictionaryOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No documentation available..
        /// </summary>
        public static string Views_DocumentationNotAvailable {
            get {
                return ResourceManager.GetString("Views_DocumentationNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible enumeration values:.
        /// </summary>
        public static string Views_EnumerationValues {
            get {
                return ResourceManager.GetString("Views_EnumerationValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Page Home.
        /// </summary>
        public static string Views_HelpPageHome {
            get {
                return ResourceManager.GetString("Views_HelpPageHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string Views_Introduction {
            get {
                return ResourceManager.GetString("Views_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Views_Name {
            get {
                return ResourceManager.GetString("Views_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None..
        /// </summary>
        public static string Views_None {
            get {
                return ResourceManager.GetString("Views_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair of.
        /// </summary>
        public static string Views_PairOf {
            get {
                return ResourceManager.GetString("Views_PairOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Formats.
        /// </summary>
        public static string Views_RequestFormats {
            get {
                return ResourceManager.GetString("Views_RequestFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Information.
        /// </summary>
        public static string Views_RequestInformation {
            get {
                return ResourceManager.GetString("Views_RequestInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Description.
        /// </summary>
        public static string Views_ResourceDescription {
            get {
                return ResourceManager.GetString("Views_ResourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Formats.
        /// </summary>
        public static string Views_ResponseFormats {
            get {
                return ResourceManager.GetString("Views_ResponseFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Information.
        /// </summary>
        public static string Views_ResponseInformation {
            get {
                return ResourceManager.GetString("Views_ResponseInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample:.
        /// </summary>
        public static string Views_Sample {
            get {
                return ResourceManager.GetString("Views_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample not available..
        /// </summary>
        public static string Views_SampleNotAvailable {
            get {
                return ResourceManager.GetString("Views_SampleNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Views_Type {
            get {
                return ResourceManager.GetString("Views_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI Parameters.
        /// </summary>
        public static string Views_URIParameters {
            get {
                return ResourceManager.GetString("Views_URIParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Views_Value {
            get {
                return ResourceManager.GetString("Views_Value", resourceCulture);
            }
        }
    }
}
